print("================================")
print("       GESTOR DE TAREAS")
print("================================")
print()
print("1. Ver tareas")
print("2. Añadir tarea")
print("3. Completar tarea")
print("4. Eliminar tarea")
print("5. Salir")